version: '3.9'
services:
  app:
    container_name: inubot-discord
    image: ghcr.io/yude/inubot-discord:master
    volumes:
      - type: bind
        source: ./data
        target: /data
    env_file:
      - ./.env
    restart: always